editAreaLoader.lang["en"]={
new_document: "új üres dokumentum",
search_button: "keresés és csere",
search_command: "következo keresése / keresési terület megnyitása",
search: "keresés",
replace: "csere",
replace_command: "csere / keresési terület megnyitása",
find_next: "következo keresése",
replace_all: "mind cserél",
reg_exp: "szokásos kifejezések",
match_case: "megegyezés esete",
not_found: "nem található.",
occurrence_replaced: "Kicserélve.",
search_field_empty: "Keresésmezo üres",
restart_search_at_begin: "Terület vége elérve. Az elején kezdd újra.",
move_popup: "keresés ablak mozgatása",
font_size: "--Betuméret--",
go_to_line: "ugrás sorra",
go_to_line_prompt: "ugrás a következo sorra:",
undo: "visszavon",
redo: "újra",
change_smooth_selection: "néhaány megjelenítési funkció engedélyezése/kikapcsolása (jobb megjalanítés, de több CPU használat)",
highlight: "szintaxis kiemelésének ki/be kapcsolása",
reset_highlight: "kiemelés újraindítása (ha eltolódik a szövegtol)",
help: "rólam",
save: "ment",
load: "tölt",
line_abbr: "sor",
char_abbr: "kar",
position: "Helyzet",
total: "Összesen",
close_popup: "felbukkanó ablak bezárása",
shortcuts: "Rövidítések",
add_tab: "tabuláció hozzáadáas a szöveghez",
remove_tab: "tabuláció eltávolítása a szövegbol",
about_notice: "Megjegyzés: Szintaxis kiemelo funkció csak kis szövegeknél muködik",
toggle: "Kapcsolószerkeszto",
accesskey: "Elérésgomb",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Feldolgozás...",
fullscreen: "teljes képernyo",
syntax_selection: "--Szintaxis--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
close_tab: "Fájl bezárása"
};
